#!/usr/bin/env node

/**
 * Build Theme Codes Sass Partial
 *
 * Generates a Sass map of theme directory → short theme code, sourced from
 * AuroDesignTokens' THEME_DEFINITIONS. This keeps WCSS's data-attribute theme
 * scoping (e.g. [data-aag-theme="aag-theme-as-type"]) aligned with the design
 * tokens' theme codes rather than hardcoding them in Sass.
 *
 * 1. Reads THEME_DEFINITIONS from @aurodesignsystem/design-tokens
 * 2. Writes src/type/mixins/_theme-codes.scss with the $wcss-theme-codes map
 *
 * The output file is generated (git-ignored) and must exist before any Sass
 * compile that imports the type mixins.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { THEME_DEFINITIONS } from '@aurodesignsystem/design-tokens/src/config/themes.js';
import { withoutExcludedThemes } from './excluded-themes.mjs';
import { STANDARD_LICENSE, createBuildReporter } from './utils/build-utils.mjs';

// Get dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// WCSS-specific overrides of the design-tokens theme code. Use this when the
// data-attribute scoping code must differ from THEME_DEFINITIONS' `code` value.
// keyed by theme directory name → the code WCSS should emit in its selectors.
const THEME_CODE_OVERRIDES = {
  'auro-1': 'atm'
};

// Output partial
const outPath = path.join(__dirname, '../src/type/mixins/_theme-codes.scss');

const reporter = createBuildReporter('Theme codes Sass partial');
reporter.start();

// Build the Sass map entries from the design tokens theme definitions
// (excluding any themes WCSS opts out of building, applying any code overrides).
const themes = withoutExcludedThemes(THEME_DEFINITIONS);
const entries = themes
  .map(theme => `  '${theme.dir}': '${THEME_CODE_OVERRIDES[theme.dir] ?? theme.code}'`)
  .join(',\n');

const contents = `${STANDARD_LICENSE}
/* --------------------------------------------------------------------- */
// AUTO-GENERATED by scripts/theme-codes.build.mjs — do not edit by hand.
// Source: @aurodesignsystem/design-tokens THEME_DEFINITIONS.
// Regenerate with: npm run build:theme-codes

// Map of theme directory name → short theme code (used to build the
// [data-aag-theme="aag-theme-<code>-type"] scoping selectors).
$wcss-theme-codes: (
${entries}
);
`;

try {
  reporter.processing('@aurodesignsystem/design-tokens/src/config/themes.js', path.relative(path.join(__dirname, '..'), outPath));
  fs.writeFileSync(outPath, contents, 'utf8');
  reporter.success(`(${themes.length} themes)`);
} catch (error) {
  reporter.processError(error);
  process.exit(1);
}
